name: 'Save and Upload Artifacts'
description: 'Saves a report URL to a file and uploads artifacts for JUnit results and report URL.'

inputs:
  job_name:
    description: 'The name of the GitHub job (used for artifact naming).'
    required: true
  junit_path:
    description: 'Path to the JUnit test results.'
    required: true
  report_url:
    description: 'The report URL to save and upload as an artifact.'
    required: false

runs:
  using: 'composite'
  steps:
    # Step 1: Upload JUnit test results as an artifact
    - name: Upload JUnit results
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: junit-${{ inputs.job_name }}
        path: ${{ inputs.junit_path }}
        retention-days: 30

    # Step 2: Save the report URL to a file
    - name: Save report URL to file
      if: ${{ inputs.report_url && !cancelled() }}
      run: echo "${{ inputs.report_url }}" > report-url.txt
      shell: bash

    # Step 3: Upload the report URL as an artifact
    - name: Upload report URL
      if: ${{ inputs.report_url && !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: report-url-${{ inputs.job_name }}
        path: report-url.txt