name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  e2e-test-1:
    container:
      image: mcr.microsoft.com/playwright:v1.50.0-noble
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Run Playwright tests
      run: npx playwright test

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: junit
        path: test-results/junit.xml
        retention-days: 30

    - name: Save report_url and title to a file
      run: |
          echo '{"report_url": "http://www.yahoo.com", "title": "${{ github.job.name }}"}' > slack-status-comment-thread.json

  e2e-test-2:
    container:
      image: mcr.microsoft.com/playwright:v1.50.0-noble
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Run Playwright tests
      run: npx playwright test

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: junit
        path: test-results/junit.xml
        retention-days: 30

    - name: Save report_url and title to a file
      run: |
          echo '{"report_url": "http://www.google.com", "title": "${{ github.job.name }}"}' > slack-status-comment-thread.json

  slack-notify:
      if: always()
      needs: [e2e-test-1, e2e-test-2]
      runs-on: ubuntu-latest
      steps:
        - name: Send Slack Notification
          uses: midleman/slack-workflow-status@mi/comment-thread
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            slack_token: ${{ secrets.SLACK_TOKEN }}
            comment_junit_failures: "true"
            comment_junit_flakes: "true"
            comment_junit_flakes_emoji: ":thumbsdown:"
            comment_junit_failures_emoji: ":skull:"
            notify_on: "always"
            channel: "U07KNKY6S5C"
