name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  e2e-test-1:
    container:
      image: mcr.microsoft.com/playwright:v1.50.0-noble
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Run Playwright tests
      run: npx playwright test

    - name: Save and Upload Artifacts for Slack Notification
      uses: ./.github/actions/workflow-status-artifacts
      if: ${{ !cancelled() }}
      with:
        job_name: ${{ github.job }}
        report_url: 'http://www.yahoo.com.com'
        junit_path: 'test-results/junit.xml'

  e2e-test-2:
    container:
      image: mcr.microsoft.com/playwright:v1.50.0-noble
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Run Playwright tests
      run: npx playwright test

    - name: Save and Upload Artifacts for Slack Notification
      uses: ./.github/actions/upload-artifacts
      if: ${{ !cancelled() }}
      with:
        job_name: ${{ github.job }}
        report_url: 'http://www.google.com'
        junit_path: 'test-results/junit.xml'

  slack-notify:
      if: always()
      needs: [e2e-test-1, e2e-test-2]
      runs-on: ubuntu-latest
      steps:
        - name: Send Slack Notification
          uses: midleman/slack-workflow-status@mi/comment-thread
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            slack_token: ${{ secrets.SLACK_TOKEN }}
            comment_junit_failures: "true"
            comment_junit_flakes: "true"
            # comment_junit_flakes_emoji: ":thumbsdown:"
            # comment_junit_failures_emoji: ":skull:"
            notify_on: "always"
            channel: "U07KNKY6S5C"
